/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Post = {
  _id: string;
  _type: 'post';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedDate?: string;
  excerpt?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  tags?: Array<string>;
};

export type Testimonial = {
  _id: string;
  _type: 'testimonial';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  testimonialText?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  rating?: number;
  dateTime?: string;
  product?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'product';
  };
};

export type ContentBlock = {
  _id: string;
  _type: 'contentBlock';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  blockType?: 'basic' | 'list' | 'categoryBlock' | 'post' | 'testimonial';
  title?: string;
  slug?: Slug;
  customAttributes?: Array<{
    key?: string;
    value?: string;
    _type: 'attribute';
    _key: string;
  }>;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  listItems?: Array<{
    title?: string;
    slug?: Slug;
    description?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }>;
    image?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    _key: string;
  }>;
  categoryBlock?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'category';
  }>;
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageType?: 'single' | 'multiple';
  title?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  layout?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'contentBlock';
  }>;
  metaTitle?: string;
  metaDescription?: string;
  metaKeywords?: Array<string>;
  variants?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'category';
  }>;
};

export type Product = {
  _id: string;
  _type: 'product';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  productType?: 'tour' | 'transport' | 'destination' | 'ticket';
  name?: string;
  slug?: Slug;
  categories?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'category';
  }>;
  price?: number;
  customPrices?: Array<{
    key?: string;
    value?: string;
    _type: 'price';
    _key: string;
  }>;
  departureDateRanges?: Array<{
    startDate?: string;
    endDate?: string;
    _key: string;
  }>;
  duration?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  bookingUrl?: string;
  features?: Array<{
    key?: string;
    value?: string;
    _type: 'feature';
    _key: string;
  }>;
  areaName?: string;
  landArea?: string;
  travelDuration?: string;
  averageClimate?: string;
  peakSeason?: string;
  midSeason?: string;
  monsoonSeason?: string;
  travelGuide?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  tourSummary?: Array<{
    isActive?: boolean;
    title?: string;
    description?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }>;
    image?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    _type: 'tourSummaryItem';
    _key: string;
  }>;
  overview?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }
  >;
  itinerary?: Array<{
    title?: string;
    description?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }>;
    images?: Array<{
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
      _key: string;
    }>;
    _type: 'itineraryItem';
    _key: string;
  }>;
  transportation?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'category';
  };
  accommodation?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }
  >;
  reviews?: Array<
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'testimonial';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'post';
      }
  >;
  thingsToNote?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }
  >;
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  parentCategory?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'category';
  };
  customAttributes?: Array<{
    key?: string;
    value?: string;
    _type: 'attribute';
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityFileAsset
  | Geopoint
  | Post
  | Testimonial
  | ContentBlock
  | Page
  | Product
  | Category
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata
  | Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries/cms.ts
// Variable: GET_PAGE_META
// Query: *[_type == "page" && slug.current == $name][0] {    _id,    slug,    metaTitle,    metaDescription,    metaKeywords  }
export type GET_PAGE_METAResult = {
  _id: string;
  slug: Slug | null;
  metaTitle: string | null;
  metaDescription: string | null;
  metaKeywords: Array<string> | null;
} | null;
// Variable: GET_PAGE
// Query: *[_type == "page" && slug.current == $name][0] {    _id,    title,    slug,    pageType,    layout[]->{      _id,      slug,      blockType,      title,      description,      image,      "imageUrl": image.asset->url,      customAttributes,      listItems[]{        title,        slug,        description,        image,        "imageUrl": image.asset->url,      },      "categories": categoryBlock[]->{        _id,        slug,      }    },    variants[]->{      _id,      title,      slug    }  }
export type GET_PAGEResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  pageType: 'multiple' | 'single' | null;
  layout: Array<{
    _id: string;
    slug: Slug | null;
    blockType: 'basic' | 'categoryBlock' | 'list' | 'post' | 'testimonial' | null;
    title: string | null;
    description: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }> | null;
    image: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    } | null;
    imageUrl: string | null;
    customAttributes: Array<{
      key?: string;
      value?: string;
      _type: 'attribute';
      _key: string;
    }> | null;
    listItems: Array<{
      title: string | null;
      slug: Slug | null;
      description: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }> | null;
      image: {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
      } | null;
      imageUrl: string | null;
    }> | null;
    categories: Array<{
      _id: string;
      slug: Slug | null;
    }> | null;
  }> | null;
  variants: Array<{
    _id: string;
    title: null;
    slug: Slug | null;
  }> | null;
} | null;
// Variable: GET_POSTS
// Query: *[_type == "post"] {    _id,    title,    slug,    publishedDate,    excerpt,    "imageUrl": image.asset->url,    content,    tags  }
export type GET_POSTSResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedDate: string | null;
  excerpt: string | null;
  imageUrl: string | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  tags: Array<string> | null;
}>;
// Variable: GET_TESTIMONIALS
// Query: *[_type == "testimonial"]{    name,    slug,    testimonialText,    "imageUrl": image.asset->url,    rating,    dateTime,    product->{      name,      slug    }  }
export type GET_TESTIMONIALSResult = Array<{
  name: string | null;
  slug: Slug | null;
  testimonialText: string | null;
  imageUrl: string | null;
  rating: number | null;
  dateTime: string | null;
  product: {
    name: string | null;
    slug: Slug | null;
  } | null;
}>;
// Variable: GET_HEADER_LAYOUT
// Query: *[_type == "page" && slug.current == "header-layout"][0] {    _id,    title,    slug,    "imageUrl": image.asset->url,    description,    layout[]->{      _id,      slug,      blockType,      title,      description,      image,      "imageUrl": image.asset->url,      customAttributes,      listItems[]{        title,        slug,        description,        image,        "imageUrl": image.asset->url,      },    }  }
export type GET_HEADER_LAYOUTResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  imageUrl: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  layout: Array<{
    _id: string;
    slug: Slug | null;
    blockType: 'basic' | 'categoryBlock' | 'list' | 'post' | 'testimonial' | null;
    title: string | null;
    description: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }> | null;
    image: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    } | null;
    imageUrl: string | null;
    customAttributes: Array<{
      key?: string;
      value?: string;
      _type: 'attribute';
      _key: string;
    }> | null;
    listItems: Array<{
      title: string | null;
      slug: Slug | null;
      description: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }> | null;
      image: {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
      } | null;
      imageUrl: string | null;
    }> | null;
  }> | null;
} | null;
// Variable: GET_FOOTER_LAYOUT
// Query: *[_type == "page" && slug.current == "footer-layout"][0] {    _id,    title,    slug,    "imageUrl": image.asset->url,    description,    layout[]->{      _id,      slug,      blockType,      title,      description,      image,      "imageUrl": image.asset->url,      customAttributes,      listItems[]{        title,        slug,        description,        image,        "imageUrl": image.asset->url,      },    }  }
export type GET_FOOTER_LAYOUTResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  imageUrl: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  layout: Array<{
    _id: string;
    slug: Slug | null;
    blockType: 'basic' | 'categoryBlock' | 'list' | 'post' | 'testimonial' | null;
    title: string | null;
    description: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }> | null;
    image: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    } | null;
    imageUrl: string | null;
    customAttributes: Array<{
      key?: string;
      value?: string;
      _type: 'attribute';
      _key: string;
    }> | null;
    listItems: Array<{
      title: string | null;
      slug: Slug | null;
      description: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }> | null;
      image: {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
      } | null;
      imageUrl: string | null;
    }> | null;
  }> | null;
} | null;
// Variable: GET_CATEGORIES_BY_PARENT_CATEGORY
// Query: *[_type == "category" && parentCategory->slug.current == $slug] {    _id,    name,    slug,    description  }
export type GET_CATEGORIES_BY_PARENT_CATEGORYResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  description: string | null;
}>;
// Variable: GET_CATEGORIES_BY_PARENT_CATEGORIES
// Query: *[_type == "category" && parentCategory->slug.current in $slugs] {    _id,    name,    slug,    description,    parentCategory-> {      _id,      slug,    }  }
export type GET_CATEGORIES_BY_PARENT_CATEGORIESResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  description: string | null;
  parentCategory: {
    _id: string;
    slug: Slug | null;
  } | null;
}>;
// Variable: GET_PRODUCTS_BY_PARENT_CATEGORIES
// Query: *[_type == "product" && references(    *[_type == "category" && parentCategory->slug.current in $categories]._id  )] {    _id,    name,    slug,    price,    "imageUrl": image.asset->url,    categories[]-> {      _id,      name,      slug,      customAttributes    },    features,    customPrices  }
export type GET_PRODUCTS_BY_PARENT_CATEGORIESResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  price: number | null;
  imageUrl: string | null;
  categories: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
    customAttributes: Array<{
      key?: string;
      value?: string;
      _type: 'attribute';
      _key: string;
    }> | null;
  }> | null;
  features: Array<{
    key?: string;
    value?: string;
    _type: 'feature';
    _key: string;
  }> | null;
  customPrices: Array<{
    key?: string;
    value?: string;
    _type: 'price';
    _key: string;
  }> | null;
}>;
// Variable: GET_CONTENT_BLOCK_BY_SLUG
// Query: *[_type == "contentBlock" && slug.current == $slug][0] {    _id,    slug,    blockType,    title,    description,    image,    "imageUrl": image.asset->url,    customAttributes,    listItems[]{      title,      slug,      description,      image,      "imageUrl": image.asset->url,    },    "categories": categoryBlock[]->{      _id,      slug,    }  }
export type GET_CONTENT_BLOCK_BY_SLUGResult = {
  _id: string;
  slug: Slug | null;
  blockType: 'basic' | 'categoryBlock' | 'list' | 'post' | 'testimonial' | null;
  title: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  image: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  } | null;
  imageUrl: string | null;
  customAttributes: Array<{
    key?: string;
    value?: string;
    _type: 'attribute';
    _key: string;
  }> | null;
  listItems: Array<{
    title: string | null;
    slug: Slug | null;
    description: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }> | null;
    image: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    } | null;
    imageUrl: string | null;
  }> | null;
  categories: Array<{
    _id: string;
    slug: Slug | null;
  }> | null;
} | null;
// Variable: GET_PRODUCT_BY_SLUG
// Query: *[_type == "product" && slug.current == $slug && productType == $type][0]{    name,    productType,    slug,    price,    customPrices,    availableDate,    duration,    description,    "imageUrl": image.asset->url,    landArea,    averageClimate,    travelDuration,    peakSeason,    midSeason,    monsoonSeason,    travelGuide,    bookingUrl,    features,    overview,    itinerary[]{      title,      "imageUrls": images[].asset->url,      description    },    accommodation,    thingsToNote,    tourSummary[]{      "imageUrl": image.asset->url,      isActive,      title,      description    },    categories[]-> {      _id,      name,      slug,      customAttributes    }  }
export type GET_PRODUCT_BY_SLUGResult = {
  name: string | null;
  productType: 'destination' | 'ticket' | 'tour' | 'transport' | null;
  slug: Slug | null;
  price: number | null;
  customPrices: Array<{
    key?: string;
    value?: string;
    _type: 'price';
    _key: string;
  }> | null;
  availableDate: null;
  duration: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  imageUrl: string | null;
  landArea: string | null;
  averageClimate: string | null;
  travelDuration: string | null;
  peakSeason: string | null;
  midSeason: string | null;
  monsoonSeason: string | null;
  travelGuide: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  bookingUrl: string | null;
  features: Array<{
    key?: string;
    value?: string;
    _type: 'feature';
    _key: string;
  }> | null;
  overview: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }
  > | null;
  itinerary: Array<{
    title: string | null;
    imageUrls: Array<string | null> | null;
    description: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }> | null;
  }> | null;
  accommodation: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }
  > | null;
  thingsToNote: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }
  > | null;
  tourSummary: Array<{
    imageUrl: string | null;
    isActive: boolean | null;
    title: string | null;
    description: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }> | null;
  }> | null;
  categories: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
    customAttributes: Array<{
      key?: string;
      value?: string;
      _type: 'attribute';
      _key: string;
    }> | null;
  }> | null;
} | null;
// Variable: GET_PRODUCTS_BY_TYPE
// Query: *[_type == "product" && productType == $type]{    _id,    name,    slug,    price,    "imageUrl": image.asset->url,    categories[]-> {      _id,      name,      slug,      customAttributes    },    features,    customPrices  }
export type GET_PRODUCTS_BY_TYPEResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  price: number | null;
  imageUrl: string | null;
  categories: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
    customAttributes: Array<{
      key?: string;
      value?: string;
      _type: 'attribute';
      _key: string;
    }> | null;
  }> | null;
  features: Array<{
    key?: string;
    value?: string;
    _type: 'feature';
    _key: string;
  }> | null;
  customPrices: Array<{
    key?: string;
    value?: string;
    _type: 'price';
    _key: string;
  }> | null;
}>;
// Variable: GET_POST_BY_SLUG
// Query: *[_type == "post" && slug.current == $slug][0]{    title,    slug,    price,    publishedDate,    excerpt,    "imageUrl": image.asset->url,    content,    tags,  }
export type GET_POST_BY_SLUGResult = {
  title: string | null;
  slug: Slug | null;
  price: null;
  publishedDate: string | null;
  excerpt: string | null;
  imageUrl: string | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  tags: Array<string> | null;
} | null;
// Variable: GET_PRODUCTS_BY_CATEGORY
// Query: *[_type == "product" && references(*[_type == "category" && slug.current == $categorySlug]._id)] {    _id,    name,    slug,    price,    "imageUrl": image.asset->url,    categories[]-> {      _id,      name,      slug,      customAttributes    },    features,    customPrices  }
export type GET_PRODUCTS_BY_CATEGORYResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  price: number | null;
  imageUrl: string | null;
  categories: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
    customAttributes: Array<{
      key?: string;
      value?: string;
      _type: 'attribute';
      _key: string;
    }> | null;
  }> | null;
  features: Array<{
    key?: string;
    value?: string;
    _type: 'feature';
    _key: string;
  }> | null;
  customPrices: Array<{
    key?: string;
    value?: string;
    _type: 'price';
    _key: string;
  }> | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "page" && slug.current == $name][0] {\n    _id,\n    slug,\n    metaTitle,\n    metaDescription,\n    metaKeywords\n  }\n': GET_PAGE_METAResult;
    '\n  *[_type == "page" && slug.current == $name][0] {\n    _id,\n    title,\n    slug,\n    pageType,\n    layout[]->{\n      _id,\n      slug,\n      blockType,\n      title,\n      description,\n      image,\n      "imageUrl": image.asset->url,\n      customAttributes,\n      listItems[]{\n        title,\n        slug,\n        description,\n        image,\n        "imageUrl": image.asset->url,\n      },\n      "categories": categoryBlock[]->{\n        _id,\n        slug,\n      }\n    },\n    variants[]->{\n      _id,\n      title,\n      slug\n    }\n  }\n': GET_PAGEResult;
    '\n  *[_type == "post"] {\n    _id,\n    title,\n    slug,\n    publishedDate,\n    excerpt,\n    "imageUrl": image.asset->url,\n    content,\n    tags\n  }\n': GET_POSTSResult;
    '\n  *[_type == "testimonial"]{\n    name,\n    slug,\n    testimonialText,\n    "imageUrl": image.asset->url,\n    rating,\n    dateTime,\n    product->{\n      name,\n      slug\n    }\n  }\n': GET_TESTIMONIALSResult;
    '\n  *[_type == "page" && slug.current == "header-layout"][0] {\n    _id,\n    title,\n    slug,\n    "imageUrl": image.asset->url,\n    description,\n    layout[]->{\n      _id,\n      slug,\n      blockType,\n      title,\n      description,\n      image,\n      "imageUrl": image.asset->url,\n      customAttributes,\n      listItems[]{\n        title,\n        slug,\n        description,\n        image,\n        "imageUrl": image.asset->url,\n      },\n    }\n  }\n': GET_HEADER_LAYOUTResult;
    '\n  *[_type == "page" && slug.current == "footer-layout"][0] {\n    _id,\n    title,\n    slug,\n    "imageUrl": image.asset->url,\n    description,\n    layout[]->{\n      _id,\n      slug,\n      blockType,\n      title,\n      description,\n      image,\n      "imageUrl": image.asset->url,\n      customAttributes,\n      listItems[]{\n        title,\n        slug,\n        description,\n        image,\n        "imageUrl": image.asset->url,\n      },\n    }\n  }\n': GET_FOOTER_LAYOUTResult;
    '\n  *[_type == "category" && parentCategory->slug.current == $slug] {\n    _id,\n    name,\n    slug,\n    description\n  }\n': GET_CATEGORIES_BY_PARENT_CATEGORYResult;
    '\n  *[_type == "category" && parentCategory->slug.current in $slugs] {\n    _id,\n    name,\n    slug,\n    description,\n    parentCategory-> {\n      _id,\n      slug,\n    }\n  }\n': GET_CATEGORIES_BY_PARENT_CATEGORIESResult;
    '\n  *[_type == "product" && references(\n    *[_type == "category" && parentCategory->slug.current in $categories]._id\n  )] {\n    _id,\n    name,\n    slug,\n    price,\n    "imageUrl": image.asset->url,\n    categories[]-> {\n      _id,\n      name,\n      slug,\n      customAttributes\n    },\n    features,\n    customPrices\n  }\n': GET_PRODUCTS_BY_PARENT_CATEGORIESResult;
    '\n  *[_type == "contentBlock" && slug.current == $slug][0] {\n    _id,\n    slug,\n    blockType,\n    title,\n    description,\n    image,\n    "imageUrl": image.asset->url,\n    customAttributes,\n    listItems[]{\n      title,\n      slug,\n      description,\n      image,\n      "imageUrl": image.asset->url,\n    },\n    "categories": categoryBlock[]->{\n      _id,\n      slug,\n    }\n  }\n': GET_CONTENT_BLOCK_BY_SLUGResult;
    '\n  *[_type == "product" && slug.current == $slug && productType == $type][0]{\n    name,\n    productType,\n    slug,\n    price,\n    customPrices,\n    availableDate,\n    duration,\n    description,\n    "imageUrl": image.asset->url,\n    landArea,\n    averageClimate,\n    travelDuration,\n    peakSeason,\n    midSeason,\n    monsoonSeason,\n    travelGuide,\n    bookingUrl,\n    features,\n    overview,\n    itinerary[]{\n      title,\n      "imageUrls": images[].asset->url,\n      description\n    },\n    accommodation,\n    thingsToNote,\n    tourSummary[]{\n      "imageUrl": image.asset->url,\n      isActive,\n      title,\n      description\n    },\n    categories[]-> {\n      _id,\n      name,\n      slug,\n      customAttributes\n    }\n  }\n': GET_PRODUCT_BY_SLUGResult;
    '\n  *[_type == "product" && productType == $type]{\n    _id,\n    name,\n    slug,\n    price,\n    "imageUrl": image.asset->url,\n    categories[]-> {\n      _id,\n      name,\n      slug,\n      customAttributes\n    },\n    features,\n    customPrices\n  }\n': GET_PRODUCTS_BY_TYPEResult;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    title,\n    slug,\n    price,\n    publishedDate,\n    excerpt,\n    "imageUrl": image.asset->url,\n    content,\n    tags,\n  }\n': GET_POST_BY_SLUGResult;
    '\n  *[_type == "product" && references(*[_type == "category" && slug.current == $categorySlug]._id)] {\n    _id,\n    name,\n    slug,\n    price,\n    "imageUrl": image.asset->url,\n    categories[]-> {\n      _id,\n      name,\n      slug,\n      customAttributes\n    },\n    features,\n    customPrices\n  }\n': GET_PRODUCTS_BY_CATEGORYResult;
  }
}
